#!/usr/bin/env python3
"""The fade ramp - ONE STEP DARKER, for every hardware colour.

CLAUDE.md 6.6 asks for "a luminance-ordered ramp toward black, kept as a
table, not as arithmetic on colour codes", and the first attempt at one
was arithmetic in disguise: scale each colour's RGB by a factor and take
the nearest of the 27. That produces `Pastel Cyan -> White -> Cyan ->
Green -> Black`, which is not a fade, it is a colour cycle - the nearest
point to a scaled cyan is a grey, because grey sits between the axes.

THE PALETTE IS A 3x3x3 CUBE AND THAT IS THE WHOLE ANSWER. Read off
docs/cpc_palette.md, every channel of every one of the 27 hardware
colours falls in one of three clusters - 0-15, 105-128, 240-255 - and
all 27 combinations are present. So a colour IS a triple of levels, and
one step darker is each non-zero level decremented: hue is preserved by
construction, no distance is measured, and nothing has to be chosen.

    Bright White (2,2,2) -> White  (1,1,1) -> Black
    Pastel Cyan  (1,2,2) -> Cyan   (0,1,1) -> Black
    Bright Red   (2,0,0) -> Red    (1,0,0) -> Black

AND IT MEANS A FADE HAS EXACTLY TWO STEPS. Three levels a channel is
three levels of brightness and there is no fourth; anything smoother
would be dithering in time, which at 25 Hz is a flicker. What makes it
read as a fade rather than two cuts is the HOLD, which is src/fade.asm's
and is counted in frames.

Emits build/fade.inc:
    FADE_DARKER     32 bytes, indexed by the hardware colour 0-31 - the
                    PORT value of the colour one step down. The five
                    values the gate array has no colour for are black,
                    because a table with a hole in it is a table that
                    can hang.
    FADE_STEPS      2 - applying FADE_DARKER this many times takes any
                    colour in the cube to black.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")

# The three clusters, read off the table rather than assumed: a channel
# is at level 0, 1 or 2 and these are the walls between them.
WALL = (64, 180)


def hardware_colours():
    rgb = {}
    for line in open(os.path.join(ROOT, "docs", "cpc_palette.md")):
        m = re.match(r"\|\s*\d+\s*\|\s*([^|]+?)\s*\|\s*(\d+)\s*\|\s*`&..`\s*"
                     r"\|\s*(\d+),(\d+),(\d+)\s*\|", line)
        if m:
            rgb[int(m.group(2))] = (int(m.group(3)), int(m.group(4)),
                                    int(m.group(5)), m.group(1).strip())
    return rgb


def level(v):
    return 0 if v < WALL[0] else (1 if v < WALL[1] else 2)


def main():
    rgb = hardware_colours()
    if len(rgb) != 27:
        raise SystemExit(f"docs/cpc_palette.md gave {len(rgb)} hardware "
                         f"colours and the gate array has 27")

    # THE CUBE, ASSERTED AND NOT ASSUMED. If a re-read of the table ever
    # put two colours on one triple, the ramp would have a colour it
    # could not reach and another it could reach twice, and the fade
    # would stick - so the mapping has to be a bijection.
    by_level = {}
    for hw, (r, g, b, name) in rgb.items():
        key = (level(r), level(g), level(b))
        if key in by_level:
            raise SystemExit(f"{name} and {rgb[by_level[key]][3]} both "
                             f"quantise to {key}: the palette is not a cube")
        by_level[key] = hw
    missing = [k for r in range(3) for g in range(3) for b in range(3)
               if (k := (r, g, b)) not in by_level]
    if missing:
        raise SystemExit(f"the cube has holes at {missing}")

    black = by_level[(0, 0, 0)]
    table = [black] * 32
    steps = 0
    for hw, (r, g, b, _) in rgb.items():
        r, g, b = level(r), level(g), level(b)
        table[hw] = by_level[(max(r - 1, 0), max(g - 1, 0), max(b - 1, 0))]
        steps = max(steps, max(r, g, b))

    out = os.path.join(ROOT, "build", "fade.inc")
    rows = []
    for i in range(0, 32, 8):
        rows.append("                db " + ", ".join(
            f"&{0x40 | table[h]:02X}" for h in range(i, i + 8)))
    open(out, "w").write("\n".join([
        "; Generated by tools/make_fade.py - do not edit.",
        "; One step toward black for every hardware colour, as the PORT",
        "; value the gate array wants. The palette is a 3x3x3 cube, so",
        "; this is each non-zero channel down one level and nothing is",
        "; chosen by distance.",
        "",
        f"FADE_STEPS      equ {steps}   ; applications that reach black",
        "FADE_DARKER:",
    ] + rows) + "\n")

    chains = []
    for hw in (11, 27, 10, 12, 20):
        c, x = [rgb[hw][3]], hw
        while x != black:
            x = table[x]
            c.append(rgb[x][3])
        chains.append(" -> ".join(c))
    print(f"-> {out}  FADE_STEPS {steps}")
    for c in chains:
        print(f"   {c}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
