#!/usr/bin/env python3
"""The HUD's art, as raw Mode 0 bytes the engine copies.

WHY THE HUD IS A BAR AND NOT THE ARTIST'S WHOLE STRIP. The mockup in
assets/sprites/common/mockup_hud.png is a full-width 16-line band -
heart, health, ammo, coins, key, oxygen - and a band like that has to
stay still while the CRTC scrolls the picture underneath it. On this
machine that means a raster split, and a raster split on a 6845 is not
a mid-frame write to R12/R13: the address latch is only reloaded from
those registers at vertical total (and, on a UM6845R, during the
scanlines of character row 0). It is `rupture' - reprogramming R4 so
the CRTC restarts a frame mid-screen - and rupture needs one precisely
timed write in the FIRST character row of each part. Neither of those
rows has an interrupt in it, so each costs a counted delay: measured
against the 6845 the firmware leaves behind, 4,588 T to reach display
line 0 from tick 2 and 4,096 more to reach line 16. ~8,700 T of a frame
with 3,548 spare (CLAUDE.md 9).

So the HUD is what the frame can pay for: a six-cell health bar at the
top left, 24x8 Mode 0 pixels, copied into place whenever the view moves
- 96 bytes, and that IS the cost, because anything screen-fixed on a
hardware-scrolled display has to be rewritten every time the start
address changes.

The cells are the artist's own: hud_bars' health_full and health_empty,
4x8 pixels each, quantised against src/palette.asm like every other
asset (CLAUDE.md 7.1) rather than against their own image.
"""
import json
import os
import sys

from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import cpclib                                                   # noqa: E402
from aseprite2spans import game_palette                         # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
ART = os.path.join(ROOT, "assets", "sprites", "common")

CELLS = ("health_full", "health_empty")


def cell_bytes(sheet, box, palette):
    """One 4x8 cell, LINE-MAJOR: two bytes a line, eight lines.

    Line-major and not column-major (which is what the TILES are stored
    in - CLAUDE.md 9) because the HUD is copied a whole line at a time
    into consecutive screen bytes, where a tile blitter paints a
    character column two bytes a raster.
    """
    pens = cpclib.quantise(sheet.crop(
        (box["x"], box["y"], box["x"] + box["w"], box["y"] + box["h"])),
        palette)
    assert box["w"] == 4 and box["h"] == 8, box
    out = bytearray()
    for y in range(8):
        for x in (0, 2):
            out.append(cpclib.encode_pixels(pens[y][x], pens[y][x + 1]))
    return bytes(out)


def main():
    js = json.load(open(os.path.join(ART, "hud_bars_cpc_mode0_sheet.json")))
    frames = js["frames"]
    if isinstance(frames, dict):
        frames = [frames[k] for k in frames]
    tags = {t["name"]: t["from"] for t in js["meta"]["frameTags"]}
    sheet = Image.open(os.path.join(
        ART, "hud_bars_cpc_mode0_sheet.png")).convert("RGBA")
    palette = game_palette(os.path.join(ROOT, "src", "palette.asm"))

    out = [f"; generated by tools/make_hud.py - do not edit",
           f"; the artist's hud_bars, 4x8 a cell, two bytes a line"]
    for name in CELLS:
        b = cell_bytes(sheet, frames[tags[name]]["frame"], palette)
        label = "HUD_CELL_" + name.split("_")[1].upper()
        out.append(f"{label}:")
        for y in range(8):
            out.append(f"                db &{b[y*2]:02X},&{b[y*2+1]:02X}")
    path = os.path.join(ROOT, "build", "hud_art.inc")
    open(path, "w").write("\n".join(out) + "\n")
    lit = sum(1 for name in CELLS[:1]
              for v in cell_bytes(sheet, frames[tags[name]]["frame"], palette)
              if v)
    print(f"-> hud_art.inc    {len(CELLS)} cells of 16 bytes, "
          f"full has {lit} non-zero bytes of 16")


if __name__ == "__main__":
    main()
