#!/usr/bin/env python3
"""A level's OWN bytes, as one packed stream for the disc.

THE MAP USED TO RIDE IN THE CORE IMAGE, which is fine for exactly one
level. `main.asm` INCBINed level_1.lvl and tileflags_level1_city.bin
into LEVEL_IMAGE at &B000 and the bootstrap LDIRed them there, so the
map, the entity table and the tile flags cost 2,200 bytes of a binary
that has to land at &4000 and relocate below it. Six levels is 13 KB of
that, and there is no 13 KB.

So a level's own bytes go on the disc with its art (CLAUDE.md 7.5) and
LEVEL_MAP_LOAD reads them at every transition - the same three steps the
banks take, minus the paging, because LEVEL_IMAGE is base RAM.

    +0     256 bytes   the tile flags, ZERO-PADDED
    +256   ...         level_<n>.lvl, exactly as the editor writes it

THE FLAGS ARE FIRST AND THEY ARE PADDED, and both halves of that are
about making MAP_INSTALL simpler rather than smaller. TILE_ATTR is 256
entries because a map byte is an index and every one of the 256 has to
answer; a padded block is ONE LDIR of a constant length into it, where
the pair of files needed a clear, a length and a second address. The
205 bytes of padding cost nothing on the disc - ZX0 eats a zero run -
and the whole image packs to about 15% either way.

AND IT IS NOT GATED BY --relink. Everything else that writes into
build/ is a generator and is skipped when the disc is being relinked
from what build/ already holds; this is not a generator, it is the
container the two files travel in. tools/test_painter.py puts the
EDITOR's level_1.lvl and tileflags into build/ and relinks - and until
those bytes reached the disc through a step that still runs, the disc
carried the previous build's level.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
BUILD = os.path.join(ROOT, "build")
LEV = os.path.join(BUILD, "levels")
sys.path.insert(0, HERE)
from build_levels import zx0                                   # noqa: E402

FLAGS_BYTES = 256               # = TILE_ATTR_N
MAX_LEVELS = 24                 # = dskdata.MAX_LEVELS, 6 environments x 4
LVL_TILESET = 9                 # header byte 9 - which ENVIRONMENT it is


def environments():
    """{environment number: its directory in build/levels}"""
    out = {}
    for d in os.listdir(LEV):
        if d.startswith("level") and os.path.isdir(os.path.join(LEV, d)):
            n = d[5:].split("_")[0]
            if n.isdigit():
                out[int(n)] = d
    return out


def found():
    """[(level number, its .lvl, its environment directory)], in order.

    A LEVEL IS A MAP AND AN ENVIRONMENT IS A BANK SET, and which one a
    level belongs to is the level's OWN word - byte 9 of its header,
    which the editor writes as its TilesetId. Pairing them off the file
    name instead would be a second statement of the same thing, and the
    day they disagreed the engine would follow the file and the build
    would follow the name.
    """
    envs, out = environments(), []
    for n in range(1, MAX_LEVELS + 1):
        lvl = os.path.join(BUILD, f"level_{n}.lvl")
        if not os.path.exists(lvl):
            continue
        env = open(lvl, "rb").read(LVL_TILESET + 1)[LVL_TILESET]
        if env not in envs:
            raise SystemExit(f"level_{n}.lvl says tileset {env} and there is "
                             f"no build/levels/level{env}_* to put it in")
        out.append((n, lvl, envs[env]))
    return out


def image(lvl_path, flags_path):
    flags = open(flags_path, "rb").read()
    if len(flags) > FLAGS_BYTES:
        raise SystemExit(f"{flags_path}: {len(flags)} tile flags, and "
                         f"TILE_ATTR holds {FLAGS_BYTES}")
    return flags + bytes(FLAGS_BYTES - len(flags)) + open(lvl_path, "rb").read()


def write_inc(biggest, which):
    """The one number main.asm needs, generated rather than written.

    LEVEL_IMAGE is at &B000 with the stack at &BFFF above it, and a
    level that outgrew the gap would corrupt the stack at the moment it
    loaded - silently, and only for that level. So the largest image the
    build actually made goes into an include and RASM does the checking,
    which is how banks.inc and disc.inc already work.
    """
    path = os.path.join(LEV, "mapimage.inc")
    open(path, "w").write("\n".join([
        "; Generated by tools/make_level_image.py",
        "; The biggest level image this build made - the tile flags, the",
        "; entity table and the map, unpacked. main.asm asserts it fits",
        "; between LEVEL_IMAGE and the stack.",
        "",
        f"LEVEL_IMAGE_SIZE        equ {biggest}      ; {which}",
    ]) + "\n")
    print(f"  -> {path}  LEVEL_IMAGE_SIZE {biggest} ({which})")


def main():
    made, biggest, which = 0, 0, "none"
    # ... and clear out any map this build did NOT make. A level that
    # was renumbered or deleted would otherwise keep its old stream on
    # the disc and its old entry in DISC_LEVEL_MAPS, which is a level
    # the game can still walk into and nothing says so.
    keep = set()
    for n, lvl_path, envdir in found():
        flags_path = os.path.join(BUILD, f"tileflags_{envdir}.bin")
        if not os.path.exists(flags_path):
            raise SystemExit(f"level_{n}.lvl is {envdir} and there is no "
                             f"{os.path.basename(flags_path)} for it")
        out = os.path.join(LEV, envdir, f"map_{n}.bin")
        os.makedirs(os.path.dirname(out), exist_ok=True)
        blob = image(lvl_path, flags_path)
        open(out, "wb").write(blob)
        zx0(out)
        keep.add(os.path.abspath(out.replace(".bin", ".zx0")))
        packed = os.path.getsize(out.replace(".bin", ".zx0"))
        print(f"-> {envdir}/map_{n}.bin  {len(blob)} bytes "
              f"({os.path.getsize(flags_path)} tile flags padded to "
              f"{FLAGS_BYTES}, {os.path.getsize(lvl_path)} of level) "
              f"-> {packed} packed, {packed / len(blob):.0%}")
        if len(blob) > biggest:
            biggest, which = len(blob), f"level_{n} in {envdir}"
        made += 1
    for d in environments().values():
        for f in os.listdir(os.path.join(LEV, d)):
            q = os.path.join(LEV, d, f)
            if (f.startswith("map_") and f.endswith(".zx0")
                    and os.path.abspath(q) not in keep):
                os.remove(q)
                os.remove(q.replace(".zx0", ".bin"))
                print(f"   (removed {d}/{f} - no level_*.lvl claims it)")
    if not made:
        raise SystemExit("no level image was made: build/ has no level file")
    write_inc(biggest, which)
    return 0


if __name__ == "__main__":
    sys.exit(main())
