#!/usr/bin/env python3
"""Image -> CPC Mode 0 screen binary.

Two targets:
    --overscan   192x272, 26,112 bytes, the title screen (default)
    --standard   160x200, 16,384 bytes, a normal 16K frame buffer

The overscan file is stored in copy order (16 raster blocks), not as two
page images, so the loader is eight LDIRs per half. See cpclib for why the
screen has to be two halves at all.

Usage:
    png2screen.py title.png -o overscan.bin --inc title_palette.asm \
                  --preview title_preview.png --dither
"""
from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cpclib

from PIL import Image


def fit(img, width, height, mode):
    if img.size == (width, height):
        return img
    if mode == "stretch":
        return img.resize((width, height), Image.LANCZOS)
    # "contain": preserve the source aspect and letterbox onto black
    scale = min(width / img.width, height / img.height)
    new = img.resize((max(1, round(img.width * scale)),
                      max(1, round(img.height * scale))), Image.LANCZOS)
    out = Image.new("RGB", (width, height), (0, 0, 0))
    out.paste(new, ((width - new.width) // 2, (height - new.height) // 2))
    return out


def quantise_dither(img, palette):
    """Floyd-Steinberg against the chosen hardware colours.

    A 3D render reduced to 16 colours bands badly without this; error
    diffusion costs nothing at runtime because it happens here.
    """
    w, h = img.size
    px = [[list(img.getpixel((x, y))[:3]) for x in range(w)] for y in range(h)]
    out = []
    for y in range(h):
        row = []
        for x in range(w):
            old = px[y][x]
            pen = cpclib.nearest_in((int(old[0]), int(old[1]), int(old[2])), palette)
            new = cpclib.HW_COLOURS[palette[pen]]
            err = [old[i] - new[i] for i in range(3)]
            row.append(pen)
            for dx, dy, f in ((1, 0, 7 / 16), (-1, 1, 3 / 16),
                              (0, 1, 5 / 16), (1, 1, 1 / 16)):
                nx, ny = x + dx, y + dy
                if 0 <= nx < w and 0 <= ny < h:
                    for i in range(3):
                        px[ny][nx][i] += err[i] * f
        out.append(row)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("image")
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("--standard", action="store_true",
                    help="160x200 16K screen instead of 192x272 overscan")
    ap.add_argument("--fit", choices=("contain", "stretch"), default="contain")
    ap.add_argument("--dither", action="store_true")
    ap.add_argument("--preview", default=None)
    ap.add_argument("--inc", default=None, help="write the palette as a RASM include")
    args = ap.parse_args()

    if args.standard:
        width, height = 160, cpclib.SCREEN_HEIGHT
    else:
        width, height = cpclib.OVERSCAN_WIDTH, cpclib.OVERSCAN_HEIGHT

    img = fit(Image.open(args.image).convert("RGB"), width, height, args.fit)

    pixels = list(img.convert("RGB").getdata())
    palette = cpclib.choose_palette(pixels, 16, forced=[20])     # pen 0 = black
    pens = quantise_dither(img, palette) if args.dither else cpclib.quantise(img, palette)

    if args.standard:
        linear = b"".join(cpclib.encode_row(row) for row in pens)
        blob = cpclib.linear_to_screen(linear, width // 2, height)
    else:
        blob = cpclib.pack_overscan(pens)

    with open(args.output, "wb") as f:
        f.write(blob)

    print(f"{args.image}: {width}x{height} Mode 0")
    print("  palette: " + ", ".join(
        f"{i}={cpclib.HW_NAMES[hw]}" for i, hw in enumerate(palette)))
    print(f"  -> {args.output}  {len(blob)} bytes")

    if args.preview:
        # Mode 0 pixels are about twice as wide as they are tall, so the
        # preview doubles the width to show the shape a monitor shows.
        prev = Image.new("RGB", (width, height))
        p = prev.load()
        for y in range(height):
            for x in range(width):
                p[x, y] = cpclib.HW_COLOURS[palette[pens[y][x]]]
        prev.resize((width * 2, height), Image.NEAREST).save(args.preview)
        print(f"  -> {args.preview}")

    if args.inc:
        name = os.path.splitext(os.path.basename(args.output))[0].upper()
        with open(args.inc, "w") as f:
            f.write("; generated by png2screen.py - do not edit\n")
            f.write(f"{name}_PALETTE:\n")
            for i, hw in enumerate(palette):
                f.write(f"                db &{cpclib.gate_array_value(hw):02X}"
                        f"      ; pen {i:2d}  {cpclib.HW_NAMES[hw]}\n")
        print(f"  -> {args.inc}")


if __name__ == "__main__":
    main()
