#!/usr/bin/env python3
"""Tile sheet PNG -> CPC Mode 0 tile binary.

Tiles are 16x16 pixels = 8 bytes x 16 lines = 128 bytes each, stored top
line first, exactly as the tilemap renderer walks them. Quantised against
the pens in src/palette.asm so tiles, sprites and HUD share one palette.

Usage:
    png2tiles.py tiles.png -o tiles.bin [--tile 16x16] [--inc tiles.inc]
"""
from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cpclib
from png2sprite import game_palette

from PIL import Image


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("sheet")
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("--tile", default="16x16")
    ap.add_argument("--palette", default=None)
    ap.add_argument("--inc", default=None)
    args = ap.parse_args()

    tw, th = (int(v) for v in args.tile.lower().split("x"))
    here = os.path.dirname(os.path.abspath(__file__))
    palette = game_palette(args.palette or os.path.join(here, "..", "src", "palette.asm"))

    sheet = Image.open(args.sheet).convert("RGB")
    if sheet.width % tw or sheet.height % th:
        raise SystemExit(f"sheet {sheet.width}x{sheet.height} is not a whole "
                         f"number of {tw}x{th} tiles")
    cols, rows = sheet.width // tw, sheet.height // th

    blob = bytearray()
    count = 0
    for ry in range(rows):
        for rx in range(cols):
            tile = sheet.crop((rx * tw, ry * th, (rx + 1) * tw, (ry + 1) * th))
            pens = cpclib.quantise(tile, palette)
            # COLUMN-MAJOR: for each character column of the tile, all
            # its lines' two bytes in a row. Every blitter paints a
            # character column at a time, so this turns the source step
            # between lines from LD A,L / ADD A,n / LD L,A into one
            # INC L. See the note at the top of src/tilemap.asm.
            for col in range(tw // 4):              # 4 pixels a character
                for line in pens:
                    blob += cpclib.encode_row(line[col * 4:col * 4 + 4])
            count += 1

    open(args.output, "wb").write(blob)
    size = tw // 2 * th
    print(f"{args.sheet}: {count} tiles of {tw}x{th}")
    print(f"  -> {args.output}  {len(blob)} bytes ({size} per tile)")

    if args.inc:
        name = os.path.splitext(os.path.basename(args.output))[0].upper()
        with open(args.inc, "w") as f:
            f.write("; generated by png2tiles.py - do not edit\n")
            f.write(f"{name}_COUNT      equ {count}\n")
            f.write(f"{name}_BYTES      equ {size}\n")
            f.write(f"{name}_WIDTH_BYTES equ {tw // 2}\n")
            f.write(f"{name}_HEIGHT     equ {th}\n")
        print(f"  -> {args.inc}")


if __name__ == "__main__":
    main()
