#!/usr/bin/env python3
"""projectile_spawn_points.json -> an assembly table.

The artist marks, on the frame where a shot leaves, the exact pixel the
projectile's left edge sits on. Hard-coding those in the engine would
mean editing Z80 every time a muzzle moves by a pixel, so they are
generated - and generated against the BLOB's frame numbering, not the
sheet's, because --drop and --tags renumber (see the *_frames.json
sidecars the exporter writes).

For a left-facing sprite the x mirrors to (frame_width - 1 - x); the
table stores the right-facing value and the engine flips it, because
that is one subtraction against doubling the table.

    <NAME>_SPAWNS:  db frame, x, y, projectile     ... and a 255 to end
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
BUILD = os.path.join(ROOT, "build", "levels")
PROJ = {"bullet": 0, "bullet_water": 1, "spear": 2, "plasma": 3,
        "laser": 4}

# which blobs come from which sheet in projectile_spawn_points.json
# (symbol, blob path under build/levels, key in the spawn-point JSONs)
BLOBS = [("KCORE", "_shared/kcore", "heroine_cpc_mode0"),
         ("KEXTRA", "_shared/kextra", "heroine_cpc_mode0"),
         ("KSWIM", "_shared/kswim", "heroine_cpc_mode0_swim")]
for lvl, who in (("level1_city", "city_agent"),
                 ("level2_forest", "forest_sniper"),
                 ("level3_cave", "cave_excavator"),
                 ("level5_desert", "desert_mercenary"),
                 ("level6_station", "station_cyber")):
    BLOBS.append((who.upper().replace("_", ""),
                  f"{lvl}/{who.replace('_', '')}", who))


def main():
    # Two files: the artist's original for the heroine, and the one in
    # common/ for the named characters that replaced the generic set.
    spec = json.load(open(os.path.join(ROOT, "assets", "sprites",
                                       "projectile_spawn_points.json")))
    chars = json.load(open(os.path.join(ROOT, "assets", "sprites", "common",
                                        "chars_spawn_points.json")))
    for k, v in chars.items():
        spec.setdefault(k, {"frame_size": [24, 64], "spawns": []})
        spec[k]["spawns"] = v
    out = ["; Generated by tools/spawns.py from "
           "assets/sprites/projectile_spawn_points.json",
           "; Frame numbers are the BLOB's, not the sheet's.",
           ""]
    for name, kind in sorted(PROJ.items(), key=lambda kv: kv[1]):
        out.append(f"PROJ_{name.upper():<14} equ {kind}")
    out.append("")
    out.append("SPAWN_END               equ 255")
    out.append("")
    total = 0
    for sym, blob, sheet in BLOBS:
        side = os.path.join(BUILD, blob + "_frames.json")
        if not os.path.exists(side) or sheet not in spec:
            continue
        src = json.load(open(side))["source_frames"]
        where = {s: i for i, s in enumerate(src)}
        rows = []
        for sp in spec[sheet]["spawns"]:
            i = where.get(sp["frame"] - 1)          # JSON counts from 1
            if i is not None:
                rows.append((i, sp["x"], sp["y"], PROJ[sp["projectile"]],
                             sp["tag"]))
        if not rows:
            continue
        total += len(rows)
        w, h = spec[sheet]["frame_size"]
        out.append(f"{sym}_SPAWNS:" + " " * max(1, 24 - len(sym) - 8)
                   + f"; {w}x{h}")
        byid = {v: k for k, v in PROJ.items()}
        for i, x, y, p, tag in sorted(rows):
            out.append(f"                db {i}, {x}, {y}, "
                       f"PROJ_{byid[p].upper()}".ljust(48) + f"; {tag}")
        out.append("                db SPAWN_END")
        out.append("")
    path = os.path.join(BUILD, "spawns.inc")
    open(path, "w").write("\n".join(out) + "\n")
    print(f"  -> {path}  {total} spawn points")
    return 0


if __name__ == "__main__":
    sys.exit(main())
