; =====================================================================
; fade.asm - the palette to black and back                    (MODULE 6)
;
; CLAUDE.md 6.6: "Fades walk each pen through a luminance-ordered ramp
; toward black and back; keep the ramp as a table, not as arithmetic on
; colour codes." The table is build/fade.inc, generated by
; tools/make_fade.py, and the reason it is generated rather than written
; is worth having here:
;
; THE PALETTE IS A 3x3x3 CUBE. Every channel of every one of the 27
; hardware colours falls in one of three clusters - 0-15, 105-128,
; 240-255 - and all 27 combinations are present. So a colour IS a
; triple of levels, one step darker is each non-zero level decremented,
; hue is preserved by construction, and FADE_STEPS is 2 because three
; levels is three levels. The first ramp written here measured distance
; to a scaled RGB instead and produced `Pastel Cyan -> White -> Cyan ->
; Green -> Black`: a grey sits nearer a dimmed cyan than a dim cyan
; does, because grey is between the axes.
;
; SO A FADE IS THREE STATES AND THERE IS NO FOURTH - full, half, black
; - and what makes it read as a fade rather than two cuts is the HOLD.
; Anything smoother would be dithering in time, which at 25 Hz is a
; flicker.
;
; IT WORKS ON A PALETTE, NOT ON THE PALETTE. The title screen is the
; artist's own sixteen colours and the game is palette.asm's (7.7), so
; the caller passes the table and the fade walks whatever is in it.
; =====================================================================

                include "fade.inc"

FADE_HOLD       equ 6           ; hardware frames a step is held. Three
                                ; states at 6 is 0.36 s of fade, which
                                ; is about what a screen transition
                                ; wants; longer and the player is
                                ; waiting for the game rather than
                                ; watching it leave.

; ---------------------------------------------------------------------
; FADE_LEVEL - put a palette up with every pen A steps toward black.
;
; IN : A  = steps, 0 = the palette as it stands, FADE_STEPS = black
;      HL = a 17-byte palette, PALETTE_LOAD's own shape
; OUT: it is on the gate array
;                                destroys AF,BC,DE,HL
;
; IT WALKS FROM THE SOURCE EVERY TIME, and that is not waste, it is the
; only way round. The gate array cannot be read back, so a fade that
; stepped the LIVE colours would need a shadow of them; and the ramp is
; not invertible anyway - three colours darken onto Black and nothing
; in the table says which one to come back to. Walking k steps down
; from the target is one loop for both directions.
; ---------------------------------------------------------------------
FADE_LEVEL:     ld   d,a
                ld   bc,GA_PORT * 256       ; C = 0 = select pen 0
.pen:           push bc
                ld   a,(hl)
                inc  hl
                ld   e,d                    ; E = steps left for this pen
.down:          ld   b,a
                ld   a,e
                or   a
                ld   a,b
                jr   z,.put
                dec  e
                push hl
                and  31                     ; the hardware colour out of
                ld   l,a                    ; the port value
                ld   h,0
                ld   bc,FADE_DARKER
                add  hl,bc
                ld   a,(hl)
                pop  hl
                jr   .down
.put:           pop  bc
                out  (c),c                  ; %00xxxxxx - select pen C
                out  (c),a                  ; %01xxxxxx - set its colour
                inc  c
                ld   a,c
                cp   16
                jr   c,.pen
                ; ... and the border with them. It is the seventeenth
                ; entry of the table and it is black in the game (9), so
                ; in practice this fades black to black - but the title
                ; screen's border is not black and a fade that left it
                ; lit would put a frame round a picture that had gone.
                ld   c,GA_PEN_BORDER
                ld   a,(hl)
                ld   e,d
.bdown:         ld   b,a
                ld   a,e
                or   a
                ld   a,b
                jr   z,.bput
                dec  e
                and  31
                ld   l,a
                ld   h,0
                ld   bc,FADE_DARKER
                add  hl,bc
                ld   a,(hl)
                ld   c,GA_PEN_BORDER
                jr   .bdown
.bput:          out  (c),c
                out  (c),a
                ret

; ---------------------------------------------------------------------
; FADE_OUT / FADE_IN - the whole ramp, a step every FADE_HOLD frames.
;
; IN : HL = the palette being left, or arrived at
;                                destroys AF,BC,DE,HL
;
; FADE_OUT ends on black and FADE_IN ends on the palette itself, so the
; pair is symmetric and either can be used alone: a level change is
; OUT, the work, IN.
;
; INTERRUPTS ARE THE CALLER'S BUSINESS. A fade is called between
; frames, where the main loop is not running - and the level load in
; the middle of a transition runs with them off anyway (7.5).
; ---------------------------------------------------------------------
FADE_OUT:       ld   (FADE_PAL),hl
                xor  a
.step:          ld   (FADE_STEP),a
                call FADE_SHOW
                ld   a,(FADE_STEP)
                inc  a
                cp   FADE_STEPS + 1
                jr   c,.step
                ret

FADE_IN:        ld   (FADE_PAL),hl
                ld   a,FADE_STEPS
.step:          ld   (FADE_STEP),a
                call FADE_SHOW
                ld   a,(FADE_STEP)
                or   a
                ret  z
                dec  a
                jr   .step

; One step: put it up and hold it. THE WAIT IS AN EDGE AND NOT A LEVEL
; - the pulse is 16 scanlines and this body is a few hundred T, so a
; bare WAIT_VSYNC would go round it four times inside one pulse and the
; whole fade would be over in a frame and a half (7.7).
FADE_SHOW:      ld   hl,(FADE_PAL)
                call FADE_LEVEL
                ld   b,FADE_HOLD
.hold:          push bc
                call WAIT_VSYNC_END
                call WAIT_VSYNC
                pop  bc
                djnz .hold
                ret

FADE_PAL:       dw 0
FADE_STEP:      db 0
